version: "3.7"
services:
  mysql:
    image: mysql:8.0.26
    container_name: lambda-reservation-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    platform: linux/x86_64
    restart: always