service: reservation
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler/index.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-esbuild
  - serverless-offline