service: reservation
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler/api/index.handler
    events:
      - httpApi:
          path: '{proxy+}'
          method: ANY

plugins:
  - serverless-plugin-typescript
  - serverless-offline