service: reservation
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  main:
    handler: src/service/api/handler.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'

plugins:
  - serverless-plugin-typescript
  - serverless-offline